
LIBFTDIR = libft-1.1
LIBFTNAME = ft
LIBFTAR = libft.a
LIBFTPATH = $(LIBFTDIR)/$(LIBFTAR)
LIBFTINCLUDES =  -I $(LIBFTDIR)/includes/
LIBFTFLAGS = -L $(LIBFTDIR)/ -l $(LIBFTNAME) $(LIBFTINCLUDES)

LIB_PATH += $(LIBFTPATH)
LIB_INCLUDE += $(LIBFTINCLUDES)
LIB_FLAGS += $(LIBFTFLAGS)
LIB_DIR += $(LIBFTDIR)

fclean ::
	$(MAKE) fclean -C $(LIBFTDIR)

$(LIBFTPATH) :
	$(MAKE) -C $(LIBFTDIR)

.PHONY: 