
LIBFTDIR = libft-1.1
LIBFTNAME = ft
LIBFTAR = libft.a
LIBFTPATH = $(LIBFTDIR)/$(LIBFTAR)
LIBFTINCLUDES =  -I $(LIBFTDIR)/includes/
LIBFTFLAGS = -L $(LIBFTDIR)/ -l $(LIBFTNAME) $(LIBFTINCLUDES)

LIB_PATH += $(LIBFTPATH)
LIB_INCLUDE += $(LIBFTINCLUDES)
LIB_FLAGS += $(LIBFTFLAGS)

$(LIBFTPATH)	: force
	$(MAKE) -C $(LIBFTDIR)

fclean ::
	$(MAKE) fclean -C $(LIBFTDIR)