
MLXDIR = minilibx-linux
MLXNAME = mlx
MLXAR = minilibx.a
MLXPATH = $(MLXDIR)/$(MLXAR)
MLXINCLUDE = -I $(MLXDIR)/
MLXFTFLAGS = -L $(MLXDIR)/ -l $(MLXNAME) $(MLXINCLUDE) -lXext -lX11

LIB_PATH += $(MLXPATH)
LIB_INCLUDE += $(MLXINCLUDE)
LIB_FLAGS += $(MLXFTFLAGS)
LIB_DIR += $(MLXDIR)

fclean ::
	$(MAKE) clean -C $(MLXDIR)

$(MLXPATH) : force 
	$(MAKE) -C $(MLXDIR)